const CREATE_RESERVATION = 'CREATE_RESERVATION'
const GET_RESERVATIONS = 'GET_RESERVATIONS'
const START_LOADING = 'START_LOADING';
const FINISH_LOADING = 'FINISH_LOADING';
const DELETE_RESERVATION = 'DELETE_RESERVATION'
export { CREATE_RESERVATION, GET_RESERVATIONS, START_LOADING, FINISH_LOADING, DELETE_RESERVATION }